# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='detailed',
            new_name='detail',
        ),
    ]
