# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='profile_image',
        ),
    ]
