# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190403_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('post', models.TextField()),
            ],
        ),
    ]
