# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190404_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(),
        ),
    ]
